version: "3"
services:
  frontend:
    container_name: frontend
    stdin_open: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "8000:8000"
