name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-docker-containers:
    name: Test Docker Containers
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        ports:
          - '3307:3306'
        env:
          MYSQL_USER: admin
          MYSQL_ROOT_PASSWORD: jayatech
          MYSQL_DATABASE: paymentphp

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker containers
        run: |
          docker compose up --build -d --wait --wait-timeout 30

      - name: Run migrations
        run: |
          docker compose exec api php artisan migrate

      - name: Run API tests
        run: |
          docker compose exec api php artisan test

      - name: Run frontend tests
        run: |
          docker compose exec frontend npm test

      - name: Run frontend lint
        run: |
          docker compose exec frontend npm run lint
          docker compose down